// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'containerFluid': string;
}
declare var cssExports: CssExports;
export = cssExports;
