// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'toggleBox': string;
  'toggleBoxOption': string;
  'toggleBoxOptionSelected': string;
}
declare var cssExports: CssExports;
export = cssExports;
