// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'pieChart': string;
  'pieChartGraphic': string;
  'pieChartLabels': string;
  'pieChartLabelsSwatch': string;
}
declare var cssExports: CssExports;
export = cssExports;
