// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'companyCard': string;
  'companyCardData': string;
  'companyCardHeader': string;
  'companyCardHeaderEnd': string;
  'companyCardNotes': string;
}
declare var cssExports: CssExports;
export = cssExports;
